### ISSUE TITLE
Onboarding Flow (Parent Ticket)

### ISSUE THREAD

**Issue by shubhamsinghbundela** [Real-Dev-Squad/website-todo-items#178]
# Refactor Onboarding Flow 
## Overview
We are planning to include in current onboarding flow a identity service, change the design and ensure end to end testing.

## User Stories:
As a new user, I want to have a clear and structured onboarding experience.

## Requirement
**1. Design:** https://www.figma.com/file/nUbzEXoWgJgUQVlQdiCiog/Status-site?type=design&node-id=1-2&mode=design&t=dzSxEN284p3FrxQo-11 (It will be updated)

**2. Complete flow with details:** https://github.com/Real-Dev-Squad/website-www/issues/589

**3. Tech Stack:** 
Frontend + Testing - EmberJS 
Backend + Testing - Express.js, chai, mocha

**4. Estimation planning:** https://docs.google.com/document/d/1nC3SrLJ6aWsDqfZwECChV9B4KUrg_muwP1yMyYDt6g4

**5. Wireframe of onboarding flow:** https://excalidraw.com/#json=wx2LOVHHbDPZsGi9uYAEz,OoP8y5GZ6nfu15siU69rIA 

**6. Onboarding Flow all discussion MOM(Wg-onboarding Discord channel):** https://discord.com/channels/673083527624916993/1069806199853285426/1143587449130455140, https://discord.com/channels/673083527624916993/1069806199853285426/1146980743684309002

#### Milestone-1

- [x] https://github.com/Real-Dev-Squad/website-www/issues/578 @shubhamsigdar1 @vinit717  
- [x] https://github.com/Real-Dev-Squad/website-www/issues/575 @vinit717 (_**Merged**_)
- [X] https://github.com/Real-Dev-Squad/website-www/issues/579 @vinit717 (_**Merged**_)
- [X] https://github.com/Real-Dev-Squad/website-www/issues/580 @shubhamsigdar1 (**_Merged_**)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/581 @shubhamsigdar1 (_**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/643 @shubhamsigdar1 (_**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/582 @shubhamsigdar1 (_**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/647 @vinit717 (_**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/654 @shubhamsigdar1 (_**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/651 @shubhamsigdar1  (_**Merged**_)

#### Milestone-2
- [x] https://github.com/Real-Dev-Squad/website-www/issues/660 @vinit717  (_**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/665 @vinit717 ( _**Merged**_)

#### Milestone-3
- [x] https://github.com/Real-Dev-Squad/website-www/issues/663 @vinit717 ( _**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/670 @shubhamsigdar1 ( _**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/682 @shubhamsigdar1 ( _**Merged**_)
- [x] https://github.com/Real-Dev-Squad/website-www/issues/714 @shubhamsigdar1 
- [ ] https://github.com/Real-Dev-Squad/website-www/issues/710 
- [ ] https://github.com/Real-Dev-Squad/website-www/issues/730 @shubhamsigdar1 

### Need to be Done : 

- **After selecting a developer from roles and then signup we need to show this** 
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/111434418/06bdfa21-05f7-4e47-ab21-132e98332c1f)
but currently, it goes to this
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/111434418/e623c3b6-074d-4a0e-98a3-b9931e7e6c1b)

- **User can move to different pages through changing query params, this should be restricted.** - @satyam73 

- **Need to refactor UI for different sizes.**  @vinit717

- **Integrate applicant's API.** @vinit717 

- **Integrate discord invite API.**  - @vinit717 

- **Refactor Identity steps UI.** - @satyam73 

- **Test the whole onboarding flow**.

- **Refactor login with GitHub first when a user comes to /join route**. - @vinit717 

- **Add screen to show pending and rejected status of application**.
