### ISSUE TITLE
Audit logs for extension request

### ISSUE THREAD

**Issue by Maheima** [Real-Dev-Squad/website-todo-items#180]
### Show any user events related to placing extension requests like when an extension request was created, when it was accepted/declined, by whom it was accepted/declined
It should be visible to the user who placed the request and the superuser.

### Backend:
- [ ] [Fetch extension request logs of a given taskID for super user](https://github.com/Real-Dev-Squad/website-backend/issues/1515)

### Frontend:
- [ ] Real-Dev-Squad/website-my#486
- [ ] Real-Dev-Squad/website-dashboard#494

ETA: 13/09/23

**Comment by Maheima** [comment]
** Extension Requests:**

*Current features:*
1. Only 1 extension request can be raised at the lifetime of a task
2. Super user can edit extension status multiple times
3. Super user can edit fields like date, reason and title

*Upcoming:*
1. Multiple E. requests can be sent by a particular user
2. Super user can update status just once.
3. Super user can also edit fields like before

- The problem now is when I make the frontend of the new one, will I show the logs of a particular task ID at once or the request ID?
- or Do I need to make changes as per the current features right now?

**Comment by Maheima** [comment]
Sent by @ankushdharkar : On an extension request, only logs related to the request should be shown
On superuser requests dashboard, for a given extension request, previous extension request logs should ALSO be shown, so while making the decision, they can see previous events

**Comment by Maheima** [comment]
Tentative wireframes:

For self user:
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/42349041/2563a81f-c39d-4682-aa6d-62c0887d5e2e)

For super user:
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/42349041/28b55059-775e-4475-9290-5ca5eaecb45e)
