### ISSUE TITLE
[RFC] Adding Analytics and Tracking to all the projects in RealDevSquad

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-todo-items#187]
**Date:** 23-09-2023
**Author:** Lakshay

# Abstract
This RFC proposes the implementation of analytics and tracking in all the projects under the RealDevSquad to collect user data, analyze website performance, and improve user experience.

# Motivation
The primary goals of this RFC are as follows:
- **Data Collection:** To gather data on user interactions and behavior.
- **Performance Analysis:** To measure website performance and identify areas for improvement.
- **User Experience Enhancement:** To enhance user experience by analyzing how users interact with forms and other interactive elements.

# Implementation Details
**1. Analytics Platform Selection**
We propose the use of Posthog as our analytics solution. This platform is chosen for the aforementioned reasons - Open-Source, Self-Hosted Option, Developer-Friendly, Active Community, Privacy and Security, Real-Time Dashboard, and Custom Event Tracking. 

**2. Tracking Code Placement**
We propose to start with the website www and identity service as they are small projects and good to start with. We will mention further details timely.
List of projects we can track:
- [Website Dashboard](https://github.com/Real-Dev-Squad/website-dashboard)
- [Website My](https://github.com/Real-Dev-Squad/website-my)
- [Website Status](https://github.com/Real-Dev-Squad/website-status)
- [Website Members](https://github.com/Real-Dev-Squad/website-members)
- [Mobile App](https://github.com/Real-Dev-Squad/mobile-app)
- [Website www](https://github.com/Real-Dev-Squad/website-www)
- [Identity Service](https://github.com/Real-Dev-Squad/identity-service)
- [Discord Slash Commands](https://github.com/Real-Dev-Squad/discord-slash-commands)
- [Website Goals](https://github.com/Real-Dev-Squad/website-goals)

**3. Data Points to be Tracked**
We will track the following data points:
- Page views
- User interactions with navigation elements
- Form submissions
- Form submission errors
- Time spent on pages

**4. Data Privacy and Compliance**
To ensure compliance with data privacy regulations:
- Implement a cookie consent banner to obtain user consent for data collection.
- Provide an easily accessible privacy policy on the website.

**5. Reporting and Data Analysis**
Use the Posthog dashboard to generate regular reports and analyze data. Create custom reports for:
- Page views and traffic sources
- Form submission rates
- User behavior on static pages
- Timeline

RFC Review Period: till 4 October 2023
Implementation Start Date: 10 October 2023 (OOO in Between)/Depends on Ankush approval on the application we use
Expected Completion Date: Will specify when the implementation starts

# Questions with suggestions:
**What platform do we use?** 

Mixpanel (**Huge free limit, Easy to use**), Posthog(**Can host it, Open-Source**)

Tried self-hosting the posthog on AWS, spun up the EC2 and made necessary arrangements, and got charged around 40 dollars in around 1 and a half weeks.
If we use the posthog cloud version, it gives us 1M events/month whereas if we use the mix panel, it gives 20M events/month and the mix panel is also easy to set up, both of them have comparable features. So I think we should use the mix panel. 

**What events should we track?**

Website Dashboard
- [ ] Page visits
- [ ] Time Spent
- [ ] Track task creation
- [ ] Track task creation errors
- [ ] Group Role Creation
- [ ] Adding group role on a discord user
- [ ] Tracking standup updates

Identity Service
- [ ] Track verification event (Verified/Blocked)
- [ ] Track health-check status
- [ ] Track profile fetching

Website www
- [ ] Track Page Visits
- [ ] Track Time Spent
- [ ] Track modal opening
- [ ] Track video play
- [ ] Track links clicked

Website Members
- [ ] User Identification
- [ ] Page Visits
- [ ] Time Spent
- [ ] Socials link clicks
- [ ] Task link clicks

**Comment by iamitprakash** [comment]
@lakshayman looks okay to me

**Comment by prakashchoudhary07** [comment]
Looks okay to me
