### ISSUE TITLE
Discord bot in rust with docker

### ISSUE THREAD

**Issue by MehulKChaudhari** [Real-Dev-Squad/website-todo-items#191]
### Functional Requirements

* We should be able to invite this bot to our servers. 
* It should be in a docker container
* The bot should provide a couple of slash commands in the server. 

### Objective 

To have a discord bot which can be invited to our servers and it should be dockerized. 

### User stories 

* As a user, I should be able to run the bot server in docker and host it somewhere. 
* As a discord server member, The bot should provide some slash commands. like `/help` etc. 

### Requirements
* [Rust](https://www.rust-lang.org/) 
* [Serenity](https://github.com/serenity-rs/serenity?fbclid=IwAR1uT8O6yy-aIgl7OSxGiD7RB9_wjRlRmZEg0pV_nM2epsHXycwf6z6KrC8) (rust library for discord api's)
* [Docker](https://www.docker.com/)

### Subtasks 

- [x] Create a dockerize rust repository with a running basic rust program. (ETA - 27/10/2023) 
- [ ] Real-Dev-Squad/todo-action-items#195 (ETA - TBD ) 
- [ ] Real-Dev-Squad/todo-action-items#196 (ETA - TBD ) 

## Acceptance Criteria:

- [ ] The bot should support few commands 
- [ ] We should be able to invite bot to our servers and project should be dockerized.

**Comment by MehulKChaudhari** [comment]
First sub-task "Create a dockerize rust repository with a running basic rust program."  is completed with [commit](https://github.com/MehulKChaudhari/rust-bot/commit/9043a5b9df3de42b58047e59135762d26b07e87d)
