### ISSUE TITLE
Update Task Status Terminology from "COMPLETED" to "DONE" in Client and Server(Parent Ticket)

### ISSUE THREAD

**Issue by shubhamsinghbundela** [Real-Dev-Squad/website-todo-items#193]
# Update Task Status Terminology from "COMPLETED" to "DONE" in Frontend and Backend

## Overview:

This ticket aims to change the task status terminology used in both the frontend and backend of our application from "COMPLETED" to "DONE." This update is essential for maintaining a consistent user experience and data integrity.

## User Stories:

- As a developer, I need to modify the frontend code and backend code to replace all instances of "COMPLETED" with "DONE" in the task status to ensure consistency for end users.
- As a user, I expect the task status to be 'DONE' both in the frontend and backend, ensuring that the information matches and is easy to understand

## Requirement:

Design Doc: 

- https://docs.google.com/document/d/1C3oizE01vH6cQHRtoJbA7-QHDoDhHuPiMllqvh6v5cM/edit?usp=sharing
- https://docs.google.com/document/d/14reXnCwvnaQcjwKgfZweSCXdvLxjjdAA7Tr_DZOqJ84/edit?usp=sharing

## Subtasks:

- [x] https://github.com/Real-Dev-Squad/website-my/issues/507
- [x] https://github.com/Real-Dev-Squad/website-my/issues/508
- [x] https://github.com/Real-Dev-Squad/website-backend/issues/1627
- [x] https://github.com/Real-Dev-Squad/website-status/issues/976
- [X] https://github.com/Real-Dev-Squad/website-status/issues/990
- [x] https://github.com/Real-Dev-Squad/website-backend/issues/1670
- [x] https://github.com/Real-Dev-Squad/website-backend/issues/1676
- [x] https://github.com/Real-Dev-Squad/website-status/issues/1012
- [x] https://github.com/Real-Dev-Squad/website-status/issues/1014
- [ ] https://github.com/Real-Dev-Squad/website-status/issues/1017
- [x] https://github.com/Real-Dev-Squad/website-my/issues/521
- [ ] https://github.com/Real-Dev-Squad/website-backend/issues/1713
