### ISSUE TITLE
Track tickets opened across RDS repos 

### ISSUE THREAD

**Issue by Ajeyakrishna-k** [Real-Dev-Squad/website-todo-items#201]
- [ ] https://github.com/Real-Dev-Squad/discord-slash-commands/issues/167

- [ ] https://github.com/Real-Dev-Squad/website-dashboard/issues/623
- [ ] https://github.com/Real-Dev-Squad/website-dashboard/issues/629
- [x] https://github.com/Real-Dev-Squad/website-dashboard/issues/630
- [x] https://github.com/Real-Dev-Squad/website-dashboard/issues/628

- [ ] https://github.com/Real-Dev-Squad/website-backend/issues/1736
- [x] https://github.com/Real-Dev-Squad/website-backend/issues/1638
- [ ] https://github.com/Real-Dev-Squad/website-backend/issues/1597
- [ ] https://github.com/Real-Dev-Squad/website-backend/issues/1302

### TODO @Ajeyakrishna-k 
- [ ] Create an Discord Image verification service
- [ ] #204
- [ ] Setup identity service in GO in AWS lambda
