### ISSUE TITLE
Bug Hunt Session Issues

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-todo-items#218]
# Bug Hunt Session Issues
#### Task listing page todo's
- [ ] redo the initial loading state for the page
   - remove the black background
- [ ] Real-Dev-Squad/website-status#1131
    - in the superuser view the card that lists all users should also be redone
    - redo the `update task progress button` button **(This is a super user only feature under feature flag) .**  
- [ ] Redesign the filter component 
- [ ] Redesign the search button
- [ ] Real-Dev-Squad/website-status#1133
    - assigned to @palakgupta2712 
- [ ] Real-Dev-Squad/website-status#1130
   - references:
       - [vercel](vercel.com)
   - [design](https://www.figma.com/file/BczpewZkFnUYpxx6tLF1Z6/Untitled?type=design&node-id=1%3A2&mode=design&t=WCl3NVrmChelGp3d-1)
   - assigned to @ajoykumardas12 

#### task details page todo's
- [ ] redesign the details page.
    - [ ] redesign the `details section`
    - assigned to @yesyash 
- [x] use sans-serif font in textarea
   - assigned to @vishalkrkamat 
- [ ] redesign the collapsable component in the `progress updates` section
    - assigned to @satyam73 
- [ ] make the tooltip component re-useable
    - [figma link](https://www.figma.com/file/BczpewZkFnUYpxx6tLF1Z6/Untitled?type=design&node-id=20%3A7626&mode=design&t=WCl3NVrmChelGp3d-1)
    - reference: 
    <img width="769" alt="image" src="https://github.com/Real-Dev-Squad/todo-action-items/assets/56453897/7baa78c1-1c3e-460b-b91f-ad83cf4452bb">
   - assigned to @skv93-coder 
- [ ] show update progress only to user the task assigned to & super users.
- [ ] redesign the descending/ascending button in the `progress update` section.
- [ ] Real-Dev-Squad/website-status#1129
    - assigned to @Achintya-Chatterjee 
- [ ] show formatted `status` instead of showing the enum directly.
- [ ] fix design for task dependencies
- [x] remove `request for task` section
   - assigned to @Pavangbhat 

#### Task progress update page
- [ ] implement the design for `task update` page
    - [figma link](https://www.figma.com/file/L1wM5fvXj3PljDoa0QLgp0/stand-up-site?type=design&node-id=8%3A89&mode=design&t=NwNc1tqd4B79w8HY-1)

**Comment by satyam73** [comment]
- [ ] Tooltip component redesign
- [x] While reloading any task detail page(Example  - https://status.realdevsquad.com/tasks/BqiWWlQJYlE1eTaKiQEZ) loading..., 404 page comes for some time, but 404 shouldn't come.
- [ ] While clicking on menu and then clicking outside of it doesn't hide menu.
- [ ] Progress update button should only be shown on task which is assigned to myself, not every task(may be we can disable it for now)
- [ ] Request task button should only be shown if task is not assigned to anyone.
- [ ] Text ellipsis for task title even if there is space in the card.

**Comment by satyam73** [comment]
- [ ] Arrow overflowing when filter menu opens
assigned to - @VinayakaHegade 
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/85296770/a33ff373-bee2-402d-9d7c-1de78c2cc097)

**Comment by satyam73** [comment]
## Cannot be assigned to anyone now!

- [ ] Have to disabel these buttons and show them to normal user(an acknowledgement shoud be there with tooltip  or toast that you're not authorized, if anyway user tries from changing code from console too, in general it should be disabled).
![image](https://github.com/Real-Dev-Squad/todo-action-items/assets/85296770/3893bb84-a59a-4dc2-80ef-cb258013a928)

**Comment by shreya-mishra** [comment]
Shall I work on the second task?

**Comment by satyam73** [comment]
> Shall I work on the second task?

Hey @shreya-mishra 
It will be decided in the event itself

**Comment by yesyash** [comment]
### Status site
### Miscellaneous
- [ ] 

#### Task listing page todo's
- [ ] redo the initial loading state for the page
- [ ] redesign and implement task details card for regular & super users.
    - in the superuser view the card that lists all users should also be redone
    - redo the `update task progress button` button **(This is a super user only feature under feature flag) .**  
- [ ] Redesign the filter component 
- [ ] Redesign the search button
- [ ] redo the tabs component
   - references:
       - [animated tabs](https://buildui.com/recipes/animated-tabs)

#### task details page todo's
- [ ] redesign the details page.
    - [ ] redesign the `details section`
- [ ] use sans-serif font in textarea
- [ ] redesign the collapsable component in the `progress updates` section
    - assigned to @satyam73 
- [ ] make the tooltip component re-useable
- [ ] show update progress only to user the task assigned to & super users.
- [ ] redesign the descending/ascending button in the `progress update` section.
- [ ] change the format of `started on` & `ends on` to `DD MMM YYY` (example: April 29, 2023)
- [ ] show formatted `status` instead of showing the enum directly.
- [ ] fix design for task dependencies

#### Task progress update page
- [ ] implement the design for `task update` page
    - [figma link](https://www.figma.com/file/L1wM5fvXj3PljDoa0QLgp0/stand-up-site?type=design&node-id=8%3A89&mode=design&t=NwNc1tqd4B79w8HY-1)
