### ISSUE TITLE
Discord Service Implementation

### ISSUE THREAD

**Issue by joyguptaa** [Real-Dev-Squad/website-todo-items#235]
### Parent Issue
- https://github.com/Real-Dev-Squad/todo-action-items/issues/231

### References
- [DISCORD SERVICE ARCHITECTURE](https://docs.google.com/document/d/1ij613NZiwm4qmYwHBfLDplefs2ayE5wS2Zjo3a2a5SU/edit#heading=h.hnwlj1kw53q6)
- [CENTRALISED DISCORD DATA MAGEMENT](https://docs.google.com/document/d/1Nv-qQ9pe_feX_ELkifmhsSKCSgM_uid0Sz95wBXZMHA/edit)

### Issue Description
This issue focuses on how we are approaching to implement the Discord service without affecting the current user flow and features. So, we will discuss everything from development to releasing & rollback strategies.

## Tech Stack
1. Coding Language: **GoLang**
2. Queue: **RabbitMQ**
3. Containerisation: **Docker Image**
4. Deployment : **ECS (Not Sure)**

## Developement
The Discord service is going to be developed in Golang. The idea is to divide the entire service into 2 parts, which are listed below.
1. A service that accepts requests from the outside world and then acts as a queue producer. It will be responsible for inserting tasks into the queue along with all the data required for consumption.
2. A consumer must be there which should keep on looking tasks from the queue and should work independently with the server as it only interacts with the queue.

## Must Have

| Name | Estimation (in hours) |
|--------|--------|
| Figure out max threshold of queue | 3 |
| List down all the tasks that currently `discord-slash-command` handles | 4 | 
| Define Priority for each Task | 2 | 
| Figure out how are we going to communicate among different services | 4 | 
| List down API rate limits, globally and route specific | 6 | 
| List out ways we can send alerts, if queue goes down, as discord bot has vast dependency  | 6 |
| Design Doc for Implementation | 6 |
| Figure out release strategy | 2 | 
| Also tackle and mention roll back strategy | 4 | 
| Connect with @prakashchoudhary07  regarding deployment strategy | 4 | 
| Actual Implementation |  40| 
| Total |  81| 

## Phase 1

- [x] Figure out max threshold of queue 
- [x] List down all the tasks that currently `discord-slash-command` handles
- [x] Define Priority for each Task
- [x] Figure out how are we going to communicate among different services
- [x] List down API rate limits, globally and route specific

## Phase 2 : 24 Sept

- [x] Design Doc for Implementation
- [x] Should have 0 failing scenarios even in case of replies
- [x] Figure out release strategy 
- [x] Define Priority for each Task
- [x] Also tackle and mention roll back strategy
- [x] Connect with @prakashchoudhary07  regarding deployment strategy

## Phase 3 : 6 - 10 Oct
- [x] Actual Implementation

## Good to have
1. Figure out why the order of messages gets changed
<img width="810" alt="Screenshot 2024-06-12 at 11 07 39 PM" src="https://github.com/Real-Dev-Squad/todo-action-items/assets/56365512/f2cc6d4d-203c-46ef-9474-a3117a915c1c">

## Current Behavior
Currently, we are not managing API rate limits globally. As a result, our system may fail at any time, for example, if it takes on 2 tasks simultaneously. Therefore, as an end user, I need to ensure that the next set of tasks is delayed.

## Expected Behavior
Expecting API rate limits to be implemented globally. Failure to do so may result in system failure, particularly if it handles multiple tasks simultaneously. Therefore, as an end user, I should not worry about API rate limits, our system should be smart enough to handle it on its own. Also it should always prioritise tasks with high priority over low priority tasks.

### Severity/Priority
 - [x] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by tejaskh3** [comment]
I have gone through this issue, just want to clarify, will we deprecate discord-slash-commands after creating this?

**Comment by joyguptaa** [comment]
> I have gone through this issue; I just want to clarify: Will we deprecate discord-slash-commands after creating this?

No, discord-slash-command is going there as we need some service to let our bot interact with. It is just instead of other services (CRON, website-backend) telling discord-service what to do we will have a single service telling discord service what to do and when to do it (by making sure of API rate limiting)

**Comment by joyguptaa** [comment]
Doc Links : 
- [1] https://docs.google.com/document/d/1ij613NZiwm4qmYwHBfLDplefs2ayE5wS2Zjo3a2a5SU/edit?usp=sharing
- [2] https://docs.google.com/document/d/1CNi5tPN5rgDMnY8EnR2LuyD8ZsbAPTGzbGWBsnB3nco/edit?usp=sharing
- [3] https://docs.google.com/document/d/1RQn2Opq7ltCIVWJf9NmQbRwrLQs_tF0f2YqX-18z3GQ/edit?usp=sharing
