### ISSUE TITLE
Remove dev feature flag from website-backend

### ISSUE THREAD

**Issue by samarpan1738** [Real-Dev-Squad/website-todo-items#248]
### Issue Description
We need to remove the `dev` feature flag for the backend APIs that have been live on prod for more than 14 days.

After going through the APIs where `dev` feature flag is being, the APIs can be divided in 3 categories
1. All usages of the API (in all repos) are using the `dev` FF
2. Partial usages of the API (in all repos) are using the `dev` FF
    1. The `dev` FF introduces breaking changes
    2. The `dev` FF does not introduce breaking changes
3. The feature behind the `dev` FF is being tested in staging/prod

### Breaking changes 
1. For `GET /users` API
    - Query param with name `query` has been renamed to `q`
2. For `Get /users/search` API
    - Add pagination when multiple filter is applied and user count greater than 100.
### Subtasks
1. For the APIs in category-1
    1. [ ] After the `dev` FF has been removed from `website-backend` which is an ongoing task 
        - https://github.com/Real-Dev-Squad/website-backend/issues/2075  
    3. [ ] Remove the `dev` FF from all the repos where it's being used (Refer the attached issue for the usages of these APIs)
        - `POST /extension-requests`
        - `POST /discord-actions/nicknames/sync`
        - `GET /logs API`
        - `GET /requests`
        - `GET /extension-requests/self`
        - `POST /requests`
        - `PUT /requests/:id`
        - `GET /tasks`
2. For `GET /users` API (category-2)
    1. [ ] Use dev feature flag for `GET /users` in `discord-slash-commands` repo
    2. [ ] Use dev feature flag for `GET /users` in `members-site` repo
    5. [ ] Use dev feature flag for `GET /users` in `mobile-app` repo
    6. [ ] Use dev feature flag for `GET /users` in `website-dashboard` repo
    7. [ ] Use dev feature flag for `GET /users` in `website-status` repo
    8. After the above changes are deployed and tested on prod
        1. [ ] Remove dev feature flag for GET /users from `website-backend` 
    9. After the above task is deployed and tested on prod
        1. [ ] Remove dev feature flag for GET /users from all the above repos where it was added
3. For `GET /users/search` API (category-2)
    1. [ ] Use dev feature flag for `GET /users/search` in `website-dashboard` repo
    2. [ ] Use dev feature flag for `GET /users/search` in `discord-slash-commands` repo
    3. After the above changes are deployed and tested on prod
        1. [ ] Remove dev feature flag for GET /users from `website-backend` 
    4. After the above task is deployed and tested on prod
        1. [ ] Remove dev feature flag for GET /users from all the above repos where it was added
4. For `GET /users/username` (category-3)
    1. [ ] Remove dev feature flag from `website-backend`
    1. [ ] Remove dev feature flag from `website-my`
