### ISSUE TITLE
Migrate to Cloudinary Images

### ISSUE THREAD

**Issue by pallabez** [Real-Dev-Squad/website-todo-items#69]
#  website-www

- [x] Real-Dev-Squad/website-todo-items#70
![image](https://user-images.githubusercontent.com/63191499/164942627-e98a38de-71c2-4ba5-bee0-dcee430f9fc4.png)
- [x] Member wheel
![image](https://user-images.githubusercontent.com/63191499/164942676-d7bf6e41-71b1-4a45-911e-ad53fa6586e1.png)

# website-welcome

- [ ] Real-Dev-Squad/website-welcome#229
![image](https://user-images.githubusercontent.com/63191499/164942708-47b2260c-e630-43af-a62f-6b693495d40f.png)

# website-event
- [x] Navbar display picture
![image](https://user-images.githubusercontent.com/63191499/164942734-071d04ef-6f95-4f17-9b3f-4a38bfee2789.png)

# website-members
- [x] Real-Dev-Squad/website-members#369
![image](https://user-images.githubusercontent.com/63191499/164942779-1dad4367-fb34-4438-9039-71da3b120e84.png)

# website-status 
- [ ] Tasks section 
![image](https://user-images.githubusercontent.com/63191499/164942852-f829cb27-4696-4930-888d-6b50b0ae7d1c.png)
- [ ] Idle members section 
![image](https://user-images.githubusercontent.com/63191499/164942884-043a7a66-d4ed-467d-92d7-a94ec2abf62f.png)
- [ ] Real-Dev-Squad/website-status#260
![Screenshot from 2022-05-12 01-10-37](https://user-images.githubusercontent.com/61227144/167932394-b3ecbb46-0eef-4b31-98a1-80384ee7d518.png)

# website-crypto
- [ ] Auctions Section
![image](https://user-images.githubusercontent.com/78433013/172313307-a76d80c6-84a9-4d92-a8ee-337f249f5d45.png)
