### ISSUE TITLE
Tasks Level Feature

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-todo-items#72]
## Progress
- [ ] Dashboard Site
   - [ ] Issue: https://github.com/Real-Dev-Squad/website-dashboard/issues/189                                                                         
          PR: https://github.com/Real-Dev-Squad/website-dashboard/pull/188
- [ ] Backend
   - [ ] (Not a major working part) Issue: https://github.com/Real-Dev-Squad/website-backend/issues/619
   - [ ] Issue: https://github.com/Real-Dev-Squad/website-backend/issues/638
   - [ ] Issue: https://github.com/Real-Dev-Squad/website-backend/issues/701 (assigned to [vinayak](https://github.com/vinayak-trivedi))
- [ ] Status Site
- [ ] My site
  - [ ] Issue: https://github.com/Real-Dev-Squad/website-my/issues/259 (available)
- [ ] Members Site
  - [ ] Issue: https://github.com/Real-Dev-Squad/website-members/issues/425 (available)
  - [ ] Issue: https://github.com/Real-Dev-Squad/website-members/issues/424 (available)

## Description Summary
- Each task we create will contain a label that is considered to be the level of that task.
- When the user completes the `n` (suppose 5) number of that level of task, they can be considered as that level of developer
- Labels can be specific to frameworks or libraries we have (like `React Level 1`).
- Dynamically handle the available tasks for any particular developer (user) - (Service)

**Comment by rohan09-raj** [comment]
## website-dashboard
- A new field to be added to assign levels to that task
For example: React Level 1, React Level 2, Ember Level 4 means as the level increases difficulty increases.

## website-status
- Categorise the tasks according to levels
- Build a categorization of Tasks
- Show only Tasks according to the level of that developer.

## website-members
- Check if the Task has `COMPLETED` status or not
- Add a badge according to what the user has accomplished 

## website-backend
- Modify Task Workflow APIs
- Add one more field to `/user/self` i.e. `skillLevel`

**Comment by rohan09-raj** [comment]
Badges can be of following types - 
![image](https://user-images.githubusercontent.com/78433013/165417543-4903d6ba-bbc6-45c4-b004-f341e02a01c2.png)
![image](https://user-images.githubusercontent.com/78433013/165416757-e4524298-0dda-4d45-ade6-435705ad8e9e.png)
![image](https://user-images.githubusercontent.com/78433013/165417602-3a62ad0d-a945-4bfb-880f-dc653272b206.png)

**Comment by rohan09-raj** [comment]
## Categorization of Tasks
- There will be various skills categories depending upon the need
- These categories will form a tree-like structure and when the user completes the certain level tasks, the skill badges are added accordingly to the user.
- Below is an example that how the nesting of categories can be.

#### Example :
**Frontend-1:** React-1, Ember-1, JS-2, CSS-2, HTML-2, Documentation-1, PR-2
**Backend-1:** NodeJS-1, JS-2, Java-1, API-2, Postman-1, Documentation-1, Communication-1
**System-Design-1:** **Frontend-1**, **Backend-1**

## Working of Tasks Assigning
Suppose a user has some certain levels already or no levels, so according to current data of the user, 
- The tasks available to assign will be skills with the lowest level.
- If there are no tasks available for the lowest level, 2nd lowest will be shown, and if 2nd lowest is also not available then 3rd and so on.
- If there are no tasks available for any category, then `Super User` should be able to assign challenges to the user like Lift-Simulation, Implement a Polyfill, or Solve this problem etc.

#### Example :
function (userId)
- Current Levels: Frontend-1, Backend-2, Communication-2
- Next Task - Lowest (F, B, S, D) = F-1      // F(n+1) = F2 ..
- Find F2 from available --- There is no F2.... Yikes!  --> Handling ... F,    nextLowest(S, D, B) = S

**Comment by rohan09-raj** [comment]
Badges can be of following types - 
![image](https://user-images.githubusercontent.com/78433013/165417543-4903d6ba-bbc6-45c4-b004-f341e02a01c2.png)
![image](https://user-images.githubusercontent.com/78433013/165416757-e4524298-0dda-4d45-ade6-435705ad8e9e.png)
![image](https://user-images.githubusercontent.com/78433013/165417602-3a62ad0d-a945-4bfb-880f-dc653272b206.png)

Skills can be shown this way like we have in GitHub -
![image](https://user-images.githubusercontent.com/78433013/166690569-eb07e2dd-d1d7-4152-955f-f8d62acf83d2.png)
![image](https://user-images.githubusercontent.com/78433013/166690674-b2f231c1-b37a-478e-b300-cfd866758316.png)

**Comment by rohan09-raj** [comment]
### Detailed Working
#### Step 1 :
**(Dashboard Site)**
Add a new field to Task i.e. Level of the Task - Typically group of Dropdowns
![image](https://user-images.githubusercontent.com/78433013/171479364-4b29d05b-132a-4ec8-987a-48f009749708.png)

Here, there can be two cases : 
- Task Status is already assigned (Jump to Step <Need to Fill>)
- Task Status is set to available (Continue with Steps)

Data gets stored with the levels
API Used: https://api.realdevsquad.com/tasks

#### Step 2 :
**(Status Site)**
Fetch the Idle Members **[Maybe it needs to be corrected according to the current user status (set in my-site)]**
Fetched Tasks Status should be 'AVAILABLE' **[It needs to be corrected according to the current task status]**
API Used: https://api.realdevsquad.com/members/idle

#### Step 3 :
Build an API that on click on taking the input of user's current levels and return back the tasks according to the level of that user. Internally it compares the level of task and the current levels of user.
Note: `Need to figure out what parameters will be actually compared`

**Rough Idea: **
1 -> Find the category with the lowest level and lowest + 1 with a minimum number of tasks done
2 -> Compare the two params i.e. category and level in tasks data with the output of `1st` Step and return the tasks if the comparison is equal.

#### Step 4 :
After the task gets assigned and as soon as marked as completed on my-site, the API call will be made on `/users/self` to update the number of tasks done and levels.

#### Step 5 :
Now we have data points to show the current levels of the user.

How do we store the User Levels ??
-> In the user data, i.e `/users/self` API
```JS
skillLevel : {
  systemDesign: {
    level: 0,
    tasksDone: 0 // This will increase on 5 tasks done or if all sub categories has reached common levels
    frontend: {
      level: 1, // With the multiples of 5 of tasksDone value, level will increase, 5 tasks -> level 1
      tasksDone: 6,
    },
    backend: {
     level: 0, // With the multiples of 5 of tasksDone value, level will increase, 5 tasks -> level 1
     tasksDone: 3
    },
    additional: {
      level: 2,
      tasksDone: 11 // With the multiples of 5 of tasksDone value, level will increase, 10 tasks -> level 2
    },
  }
}
```

How do we store the task levels?
-> In the task data, we send level like this :
```JS
tasks:[{
  id:"CHthCdHcINQJoa6oBWSX",
  type: "feature",
  title:"Test One day task",
  purpose: "To check if everything is working",
  isNoteworthy: false,
  percentCompleted: 0,
  status: "ASSIGNED",
  createdBy: "ankush",
  assignee: pallab, 
  startedOn:1651084680.586,
  endsOn:1652294280.586,
  taskLevel: {
   category: "frontend",
   level: 2
  }
  completionAward: {
    dinero: 0,
    neelam: 0
  },
  lossRate: {
    dinero: 0,
    neelam: 0
  },
}]
```

### Existing APIs Used
https://api.realdevsquad.com/tasks
https://api.realdevsquad.com/members/idle
https://api.realdevsquad.com/users/self

### New APIs needed to be created
https://api.realdevsquad.com/tasks/TBD

**Comment by rohan09-raj** [comment]
Availability Panel
Method -> Clicking on the tasks will render the eligible idle members

Bug Observed => Setting user status is not working in status site

**Comment by rohan09-raj** [comment]
## Sequence Diagram for Tasks Level Feature
![TaskLevelFeature_Sequence](https://user-images.githubusercontent.com/78433013/172022238-931a3860-822c-4e19-912a-245f47e3b9b1.png)

**Comment by vinayak-trivedi** [comment]
### Additional suggestions

- when a user creates an account with RDS he is automatically assigned lift simulation and it appears on his my site tasks, and when he completes it then he is assigned a task based on the info he provided about his skills on a form that will be provided in my site.

**Comment by vinayak-trivedi** [comment]
### Milestone 1 

- Add a field to my site called `skill level` which is going to contain three subfields: `frontend`, `backend`, and `system design` for now. Those subfields are going to have a dropdown to select the level. Currently, there will be five levels `1 - 5`. 

- If the user has any field level less than 2 then he will be assigned a task like lift simulation or progress bar or something else.

- Upon completion of that task only the user will be assigned an RDS task.

- If all the categories are above level 2 then the user will be assigned a RDS task directly.

- Tasks are needed to have a field called `taskLevel` which will contain `category` and `level` subfields. For this, we need some more fields on the dashboard site like category and level. (PR for this is already raised by Rohan)

- An API is needed to be made which will take the `category` and `level` as `route params` and return a task accordingly (assigned to me).

- on completion of a task two API calls will be made to `user/self` and tasks/:skill/level` endpoint, and the user's skill level object will be updated and a new task will be assigned to him

**Comment by vinayak-trivedi** [comment]
### Questions: 
1. How are we going to determine the skill level of the user in the beginning?

2. we want to assign a task to the user automatically when he completes a task that was provided to him. For that, an API has been created ( [draft PR raised today](https://github.com/Real-Dev-Squad/website-backend/pull/703) ) which will return a task based on the skill level of the user, but to assign it we need to change the task object by making a patch request to `tasks/:id` which will require a super_user role to update that task. So how are we going to change that task object to assign that to a dev?

**Comment by Mir-SA** [comment]
- ### Suggestion
	- After task is completed, we can add skill & skill lvl of that task to skill model & create ref to user who completed task, Instead of Step 4 & 5 in https://github.com/Real-Dev-Squad/todo-action-items/issues/72#issuecomment-1144031642
	- Because in current design, skillLevel is a `map` stored in user document which can likely grow quickly and hit doc size limit
	- using a different collection/sub-collection for skills can help avoid the limit

- ### Differences
	- skillLevel in TL design are nested & related unlike skills in SM design https://github.com/Real-Dev-Squad/website-data-models/issues/9#issue-1367273032 which are standalone & independent
	- Skill in TL are fixed. since there would 4 options on dashboard only. Opt => 1. Sys Design 2. FE 3. BE 4. Other
	- Unlike in SM where they were assumed dynamic. Likely from text input on dashboard 

- If we have to implement the suggested change we'll have to change the skill model or change the way input is given from dashboard

**Comment by vinayak-trivedi** [comment]
As per the discussion in the main call on 22/09/2022, we want to give the super user the option to add tags of skill to a particular user, rather than assigning it automatically, the super user will get different events on the dashboard related to the task

**Comment by vinayak-trivedi** [comment]
### Progress updates of task leveling feature

1. PR merged for middleware which will be used to assign tasks to the user based on their skill levels https://github.com/Real-Dev-Squad/website-backend/pull/708
2. Frontend PR to tell users that the task is completed and a new task will be given to them is raised https://github.com/Real-Dev-Squad/website-my/pull/276
3. @ivinayakg  has raised a PR to create logs of the task updation https://github.com/Real-Dev-Squad/website-backend/pull/725
4. I am working on another issue that will show all the logs to the superuser on the dashboard site, draft PR https://github.com/Real-Dev-Squad/website-dashboard/pull/222
5. Murlidhar is working on a task that allows the super user to edit the task category and level of the task https://github.com/Real-Dev-Squad/website-status/issues/316, he will raise the PR by tomorrow as per our discussion
6. @Mir-SA is working on the user skill model https://github.com/Real-Dev-Squad/website-data-models/pull/11/files#r979428244

**Comment by vinayak-trivedi** [comment]
### Limitation of task assigning middleware

- it runs only when the user completes a task, so if a user is not assigned a task, task will not be automatically assigned to them
- and even if they are assigned a task then also there is no guarantee that they will be assigned a task once they complete the given task, as there might be no task matching their skill level

### Solution
- we can make and schedule cloud functions to run every 10 days to check which users do not have a task, and assign them a task based on their skills.

**Comment by vinayak-trivedi** [comment]
### Features in the first version of task leveling

- Add levels to the tasks
- Automatic assignment of task based on skills once the user completes their task
- logs of all the tasks
- An option for user to fetch task if they have no in-progress task
- Suggested user option to the super user when they are completing the tasks
- provide skills to the users
- providing skills and levels to tasks
- admin panel for creation of task skills and levels ( we can add more features to the admin panel in future)

### PRs needed to be merged

- task assignment endpoint enhancement https://github.com/Real-Dev-Squad/website-backend/pull/820 ( prakash added some comments replied to them)
- admin panel https://github.com/Real-Dev-Squad/website-dashboard/pull/249 ( prakash had a comment, will work on that and PR will be raised by today only)
- suggested users front end https://github.com/Real-Dev-Squad/website-dashboard/pull/250 (merged)
- provide tags to user https://github.com/Real-Dev-Squad/website-dashboard/pull/251 ( needed to be approved and merged)
- provide tags to tasks https://github.com/Real-Dev-Squad/website-status/pull/322 (needed to be approved and merged)
- logs backend https://github.com/Real-Dev-Squad/website-backend/pull/725/files# (can be merged)

### index that needed to be created
https://github.com/Real-Dev-Squad/website-backend/issues/828

**Comment by vinayak-trivedi** [comment]
### Things that are required to be done as per the latest suggestions
- task assignment API can be improved in terms of reads (will be done in another PR, for now we can start using it [issue ticket](https://github.com/Real-Dev-Squad/website-backend/issues/843))
- DB field should either be camelCase or there should be an underscore between two words (done)
- Some minor changes in depaiyan's PR as per the suggestions given by Ankush (done)

ETA for completing all these: 30/11/2022
