### ISSUE TITLE
[RFC] Task Details Page

### ISSUE THREAD

**Issue by palakgupta2712** [Real-Dev-Squad/website-todo-items#77]
## Overview

- Each task we create from dashboard site and displayed on the status site will be redirect to its specific detailed page.
- Each task will have complete details.

## Requirements

- https://github.com/Real-Dev-Squad/website-status/issues/249
 - [x] Link each task to it's specfic task details page.
 - [x] each detail page should have the following components
      - [x] Title of the task
      - [x] Description of the task
      - [x] Details of the task
      - [ ] Activity Log
      - [x] Participants
      - [x] Dates 
      
## Table of Contents 
- [Website-link](https://status.realdevsquad.com/)
- [Project Tracking](https://github.com/orgs/Real-Dev-Squad/projects/9/views/1)
- [Mockups](https://github.com/Real-Dev-Squad/website-todo-items/issues/77#issuecomment-1134867911)
- [Frontend part](https://github.com/Real-Dev-Squad/website-todo-items/issues/77#issuecomment-1120443201)
- [Backend part](https://github.com/Real-Dev-Squad/website-todo-items/issues/77#issuecomment-1134867149)

**Comment by palakgupta2712** [comment]
## Wireframe for the task details page.

![MacBook Pro 14_ - 3](https://user-images.githubusercontent.com/61227144/167303707-1e1c729b-53da-4263-83bf-b0753037a356.png)

**Comment by palakgupta2712** [comment]
### Title of the task 

### Description of the task 
- Here the description of the task will come. It can contain links, images or text.

### Details of the task 
We can have few new fields for the details of the task.
- Type 
- Priority
- Status
- Label 
   https://github.com/Real-Dev-Squad/website-todo-items/issues/72
- Feature link

### History/Activity Log
We can have the log for the changes/updation in the task after the creation of the task.
- https://github.com/Real-Dev-Squad/website-todo-items/issues/34

### Participant 
- Asignee
- Reporter

### Dates
- Created at
- Estimated time to complete
- Last Updated at
- Completed at

## Repos: 
  ### [website-status](https://github.com/Real-Dev-Squad/website-status)

**Comment by palakgupta2712** [comment]
# Tasks Details Page - backend

### Background
- Currently we have task cards in each categories on status site.
- We are planning to create a task details page for every task in the status site. 

## APIs to be used 
https://api.realdevsquad.com/tasks

response : 
``` 
{
  "title": "Title of the task",
  "purpose": "<why is this task needed>, optional",
  "featureURL": "<live url of the feature>, optional",
  "type":"feature | group",
  "links": [
    // optional
    <link1>,
    <link2>
  ],
  "endsOn":"<epoch>",
  "startedOn":"<epoch>",
  "status": "active | assigned | unAssigned | blocked | completed",
  "createdBy":"<userId>",
  "assignee":<userId> (in case of individual tasks)",
  "percentCompleted": 0,
  "dependsOn": [
    // optional
    <task_id>,
    <task_id>
  ],
  "participants": [
    // for group tasks
    // optional
    <user_id>
    <user_id>
  ],
  "completionAward": { dinero: 1500, neelam: 1 },
  "lossRate": { dinero: 100 }  // Loss per day of overshoot after deadline,
  'isNoteworthy': true
}
```
## Tasks to be done:
- [x] Add new fields into the tasks api data
      - 
           
          { 
            taskNo: <integer>, 
            priorty: <High/Medium/Low>, 
          }
(needs to be updated)
        
- [ ] Create an endpoint for logging tasks changes similar to 
      https://api.realdevsquad.com/logs/PROFILE_HEALTH
      
      - Refer - https://github.com/Real-Dev-Squad/website-todo-items/issues/34
      - Endpoint to be created - https://api.realdevsquad.com/logs/TASKS

## Repos: 
  ### [website-backend](https://github.com/Real-Dev-Squad/website-backend)
  ### [website-api-contracts](https://github.com/Real-Dev-Squad/website-api-contracts)

**Comment by palakgupta2712** [comment]
## Mockup
![MacBook Pro 14_ - 3](https://user-images.githubusercontent.com/61227144/169860846-aff4e240-b4fe-4674-9a3b-fe5d0dc758e8.png)

**Comment by rupal-2505** [comment]
@ankushdharkar Can we use purpose from API as description?
but description of task must be the explanation of the task.., right..?

**Comment by YashJain24-chief** [comment]
@ankushdharkar Can you give some clarity on the following:
1. Description for the details page: Where will it come from? Can we use `purpose` as a description or do we need a new input field in the dashboard site?
2. Task number that is to be added to tasks API: How is the task number going to be generated?
3. Priority that is to be added to tasks API: Do we need a drop-down on the dashboard site to choose from High/Medium/Low priority?

**Comment by rupal-2505** [comment]
@YashJain24-chief 
I had discussion on it with @ankushdharkar .
here are the clarifications:
1. `Description` is `purpose`.
2. `Task number` is auto generated `Document id`.
3. yeah we need to add a dropdown for priority .

**Comment by rupal-2505** [comment]
@ankushdharkar 
1. What's the purpose of `Available task` component here? Or we can remove it?
2. Purpose of `Edit button` and is it for superuser only?
3.  `Activity` component is for superuser?

**Comment by rupal-2505** [comment]
@YashJain24-chief 
1. `Available task` component should be removed as no need of that here.
2. `Edit button`  is for every user so that they can edit the description or title of the task.
3. `Activity` component is for every user.

**Comment by YashJain24-chief** [comment]
@rupal-2505 @ankushdharkar 
The edit button is for everyone or for the one's who are atleast authenticated/signed in to RDS website?
