### ISSUE TITLE
Sign out feature on all websites

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-todo-items#99]
## Issue:
- Currently, most of our pages (subdomains) do not have an option to sign out, so the user is stuck after logging in. This ticket is a major ticket wrapping the issue in all the sites where the issue is found

## Role of the ticket:
- Issue tracker for signout option on all pages
- Issue link and checkboxes to mark completed issues

## List of websites with this problem

- [x] | [website-www](https://github.com/Real-Dev-Squad/website-www) | https://github.com/Real-Dev-Squad/website-www/issues/267 | [default site](https://www.realdevsquad.com) |
- [x] | [website-welcome](https://github.com/Real-Dev-Squad/website-welcome) | https://github.com/Real-Dev-Squad/website-welcome/issues/234 | [welcome site](https://welcome.realdevsquad.com/) |
- [x] | [website-www](https://github.com/Real-Dev-Squad/website-www) | https://github.com/Real-Dev-Squad/website-www/issues/273 | [Events page](https://www.realdevsquad.com/events.html ) |
- [ ] | [website-members](https://github.com/Real-Dev-Squad/website-members) | https://github.com/Real-Dev-Squad/website-members/issues/418 | [Members site](https://members.realdevsquad.com/) |
- [x] | [website-crypto](https://github.com/Real-Dev-Squad/website-crypto) | https://github.com/Real-Dev-Squad/website-crypto/issues/284 | [Crypto Site](https://crypto.realdevsquad.com/) | 
- [x] | [website-my](https://github.com/Real-Dev-Squad/website-my) | https://github.com/Real-Dev-Squad/website-my/issues/256 | [My Site](https://my.realdevsquad.com/) |
- [x] | [website-status](https://github.com/Real-Dev-Squad/website-my) https://github.com/Real-Dev-Squad/website-status/issues/346 | [Status Site](https://status.realdevsquad.com/) |

## Description
- A path has been set up in the backend for signout which is `/auth/signout` 
- The frontend must send a `GET` request to the specified path
- After the request is completed the page must reload
- This task is already completed on the main site you can refer to the issue there along with the link to the PR.
- The backend-related PR is attached to every issue so that you don't come to this page to check it out every time.
